### ISSUE TITLE
How do I use the YOLOv8 model in this library?

### ISSUE THREAD

**Issue by DarkiT** [swdee/go-rknnlite#1]
Thank you very much for sharing this library. I want to implement object detection using YOLOv8, but I've been struggling for a long time and don't know how to proceed. I hope to return the detected data in the format [[x1, y1, x2, y2, object_type, probability], ...]. How should I write my code? Could you provide a demo?

**Comment by swdee** [comment]
At the moment I have only used the code for Image Classification models.   I am currently doing a port of the C code for Object Detection using [YOLOv5](https://github.com/airockchip/rknn-toolkit2/tree/v1.6.0/rknpu2/examples/rknn_yolov5_demo/src).

There is some code for [YOLOv8](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolov8/cpp) which I can take a look at once v5 is completed.

**Comment by swdee** [comment]
I have completed the YOLOv5 code on [this branch](https://github.com/swdee/go-rknnlite/blob/dev-yolov5/example/yolov5/README.md), will start work on writing a post processor for YOLOv8.

**Comment by swdee** [comment]
I have added an example for using YOLOv8.  Check it out and let me know how it goes?
