### ISSUE TITLE
Add object tracking feature/example to YOLO

### ISSUE THREAD

**Issue by c1ngular** [swdee/go-rknnlite#10]
it would be great if this project could not only detect but also track objects , it seems handy using ByteTrack i found [here](https://github.com/ifzhang/ByteTrack/tree/3434c5e8bc6a5ae8ad530528ba8d9a431967f237/deploy/ncnn/cpp/src) and with YOLOx [here](https://github.com/Qengineering/YoloX-Tracking-ncnn-RPi_64-bit/tree/main/src)  on raspberry pi , both based on NCNN C++.  i think the performance will be a lot better on rknn?  would you consider supporting it ? 

thanks

**Comment by swdee** [comment]
I have had someone else ask about object tracking and doing an example is possible.  There are a number of algorithms around to achieve tracking that could be implemented in the post processing stage, the question would be what is most useful?

* SORT
* DeepSORT
* ByteTrack
* Something else?

**Comment by c1ngular** [comment]
the links from my post using ByteTrack , here  [Ultralytics YOLO](https://docs.ultralytics.com/modes/track/) , it uses BoT-SORT and ByteTrack, which i have no idea why, but both seems working pretty well on video demos.

**Comment by swdee** [comment]
I have added a new example that makes use of ByteTrack for object tracking, see [Stream Example](https://github.com/swdee/go-rknnlite/tree/master/example/stream)

**Comment by c1ngular** [comment]
@swdee great job , with detailed testing results, greatly appreciated.
