### ISSUE TITLE
When there is no power to process video runtime, RAM usage increases and start freezing 

### ISSUE THREAD

**Issue by armen181** [swdee/go-rknnlite#20]
When I use only one core of RK3588 NPU, the app starts using more RAM and video freezing: 
<img width="1720" alt="image" src="https://github.com/user-attachments/assets/e74fc8fa-3d76-401f-ab32-866d376b3c90">
in the case when I use more than one NPU core there is no 
<img width="1697" alt="image" src="https://github.com/user-attachments/assets/6437c8c0-7cf7-4d65-9405-0cfd54e2b6db">

**Comment by swdee** [comment]
From the filename it appears your running a Yolov5 Medium size model and the statistics at the top when running a single NPU core indicate inference time is 6.6 seconds.      The video would be freezing up as its not playing back in real time and the memory is probably increasing as a goroutine starts for every frame being sent at 30 FPS.

When you use more than 1 core there is no problem, so the issue would be that a Medium sized model can't run on a single NPU core.   

As Yolo models require more NPU power, I recommend you run a pool size (flag `-s`) with 3, 6, or 9.

**Comment by armen181** [comment]
I guess I need to show it with a video. It seems there is buffering going on, and because the RK3588 cannot process it, RAM usage increase over time.

https://www.youtube.com/watch?v=cw6WifNyIys

**Comment by swdee** [comment]
Thanks for the video, it does show what I explained above.      

A Yolo model needs more NPU power than one core and the bytetrack example is designed to process video frames in parallel using `-s 3` or `-s 6` for best performance.     

There is a lot of buffering occurring as RAM is allocated for each video frame.  As a single NPU core can't keep up more RAM is allocated than gets freed, so eventually the linux kernel kills the program with an OOM (signal: killed).

I suspect if you changed the [FPS variable](https://github.com/swdee/go-rknnlite/blob/c28fd9bf04d7e805a1634d480b7da4565c60f244/example/stream/bytetrack.go#L24) from 30 to 10 and run with single core, it will work ok.

**Comment by armen181** [comment]
ok thanks
