### ISSUE TITLE
Fix for rk3566

### ISSUE THREAD

**Issue by mititch** [swdee/go-rknnlite#22]
First of all appreciate for you work, but have small feature request to run on rk3566 (and probably some others SoCs).

From https://github.com/rockchip-linux/rknpu2/blob/master/runtime/RK356X/Linux/librknn_api/include/rknn_api.h#L518

<img width="452" alt="image" src="https://github.com/user-attachments/assets/7b433259-f743-4dcb-8f3d-f9728beb8212">

By disabling this check https://github.com/swdee/go-rknnlite/blob/master/runtime.go#L123 it were able to run examples on rk3566 (of course with models compiled this target).

Please make this check optional for now rk3588 targets.

**Comment by swdee** [comment]
Thanks for the report, I have just pushed a change now to skip the setCoreMask() call.   You can now do the following;

```
rt, err := rknnlite.NewRuntime(*modelFile, rknnlite.NPUSkipSetCore)
```
