### ISSUE TITLE
 Do you plan to continue implementing Car Plate Recognition and Image Segmentation?

### ISSUE THREAD

**Issue by DarkiT** [swdee/go-rknnlite#3]
I used the Yolov8 interface library, which was great. I used an RK3566 TV box to solve the problem of strangers entering my home. Do you have any plans to continue implementing Car Plate Recognition and Image Segmentation?

**Comment by swdee** [comment]
Glad the YOLOv8 inference is working well for you.  

As the library is about providing a wrapper for Go to the RKNN-Toolkit for NPU acceleration I wouldn't implement Car Plate Recognition.   However you could do this quite easily with the following process.

1) Use a YOLOv8 model for license plate detection, this will allow you to identify the region in the image with license plate.   
2) Use GoCV to crop the image to the license plate region.
3) Send the cropped image to OCR software like [gosseract](https://github.com/otiai10/gosseract) to get the number plate as Text.

There is code in the RKNN Model zoo for [YOLOv5-seg](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolov5_seg) and [YOLOv8-seg](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolov8_seg) which I could port to Go, however I don't have a time line for that yet.

**Comment by swdee** [comment]
I see in the model zoo it has an [LPRNet example](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/LPRNet).

**Comment by DarkiT** [comment]
> I see in the model zoo it has an [LPRNet example](https://github.com/airockchip/rknn_model_zoo/tree/main/examples/LPRNet).

Yes, I also saw this demo in the model zoo, but because I don't know cgo, that's why I'm consulting you here to see if you have any plans. If it's too troublesome, then forget about it. I'll continue using exec to call executable programs for implementation.

**Comment by swdee** [comment]
Coincidentally I was working on the [LPRNet demo](https://github.com/swdee/go-rknnlite/tree/master/example/lprnet) when you commented, just finished it today.

The LPRNet code however is not a full license plate recognition system (ALPR), so I am curious to know how you are using it?

From the example code we have 2 out of 3 things needed for a full ALPR system.
* Vehicle detection: Yolov5 model using COCO dataset
* License plate detection: LPDNet (still needed)
* License plate recognition: LPRNet

**Comment by swdee** [comment]
I wrote an [ALPR demo](https://github.com/swdee/go-rknnlite/tree/master/example/alpr) today which combines Yolov8 and LPRNet models together.

**Comment by swdee** [comment]
I have added Instance Segmentation examples using YOLOv5-seg and YOLOv8-seg.
